rvm:
  - 1.9.3
  - 2.1.10
  - 2.3.3

branches:
  only:
    - release

before_install:
  - gem install rubygems-update --version 1.8.26
  - update_rubygems --version=1.8.26

before_script: "./bin/ci/before_script"

bundler_args: ''

script: "bundle exec rake spec"

notifications:
  recipients:
    - avonderluft@avlux.net

env:
  - DB=sqlite
  # - DB=mysql
  # - DB=postgres
