rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode

before_install: "gem install bundler --pre"

before_script: "./bin/ci/before_script"

script: "bundle exec rake spec"

notifications:
  recipients:
    - ci@spanner.org
    - git@johnmuhl.com
  irc: "irc.freenode.org#radiantcms"

env:
  - DB=mysql
  - DB=postgres

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode