rvm:
  - 1.8.7
  - 1.9.3

branches:
  only:
    - master
    - 1.x

before_install: "gem install bundler --pre"

before_script: "./bin/ci/before_script"

bundler_args: ''

script: "bundle exec rake spec"

notifications:
  recipients:
    - ci@spanner.org
    - git@johnmuhl.com
    - ci@monkeypatch.be
  irc: "irc.freenode.org#radiantcms"

env:
  - DB=mysql
  - DB=postgres
