rvm:
  - 2.3.4

before_install:
  - rm -f Gemfile
  - gem install -v 1.17.3 bundler

before_script: bin/ci/before_script

bundler_args: --without development

script: bundle exec rake spec

notifications:
  recipients:
    - ci@spanner.org
  irc: "irc.freenode.org#radiantcms"

env:
  - DB=mysql
  - DB=postgres

gemfile:
  - rails40.gemfile
