rvm:
  - 1.9.3
  - 2.0.0
  # - jruby-19mode

before_script: "./bin/ci/before_script"

bundler_args: "--without development"

script: "bundle exec rake spec"

notifications:
  recipients:
    - ci@spanner.org
    - git@johnmuhl.com
  irc: "irc.freenode.org#radiantcms"

env:
  - DB=mysql
  - DB=postgres

matrix:
  allow_failures:
    - rvm: 2.0.0
    # - rvm: jruby-19mode
