rvm: "1.8.7"
script: "bundle exec rake spec"

before_script:
  - "cp config/database.sqlite.yml config/database.yml"
  - "bundle exec rake db:migrate"
  - "bundle exec rake db:migrate:extensions"

notifications:
  recipients:
    - radiantcms-ci@googlegroups.com
    - ci@spanner.org
    - git@johnmuhl.com
  irc: "irc.freenode.org#radiantcms"
