rvm:
  - 1.8.7
  - 1.9.2

before_script: "./bin/ci/before_script"

script: "bundle exec rake spec"

notifications:
  recipients:
    - radiantcms-ci@googlegroups.com
    - ci@spanner.org
    - git@johnmuhl.com
  irc: "irc.freenode.org#radiantcms"

env:
  - DB=mysql
  - DB=postgres
